export const aiModels = [
  {
    provider: "openai",
    modelName: "GPT-4o",
    modelVersion: "2025-01-15",
    apiIdentifier: "openai/gpt-4o",
    contextWindow: 128000,
    costPer1kTokens: 0.005,
    isActive: true,
  },
  {
    provider: "openai",
    modelName: "GPT-4o-mini",
    modelVersion: "2025-01-15",
    apiIdentifier: "openai/gpt-4o-mini",
    contextWindow: 128000,
    costPer1kTokens: 0.00015,
    isActive: true,
  },
  {
    provider: "anthropic",
    modelName: "Claude Opus 4.5",
    modelVersion: "20251101",
    apiIdentifier: "anthropic/claude-opus-4.5",
    contextWindow: 200000,
    costPer1kTokens: 0.015,
    isActive: true,
  },
  {
    provider: "anthropic",
    modelName: "Claude Sonnet 4.5",
    modelVersion: "20250929",
    apiIdentifier: "anthropic/claude-sonnet-4.5",
    contextWindow: 200000,
    costPer1kTokens: 0.003,
    isActive: true,
  },
  {
    provider: "google",
    modelName: "Gemini 2.0 Flash",
    modelVersion: "exp-0205",
    apiIdentifier: "google/gemini-2.0-flash-exp",
    contextWindow: 1048576,
    costPer1kTokens: 0.0,
    isActive: true,
  },
  {
    provider: "meta",
    modelName: "Llama 3.3 70B",
    modelVersion: "versatile",
    apiIdentifier: "meta-llama/llama-3.3-70b-instruct",
    contextWindow: 8000,
    costPer1kTokens: 0.00059,
    isActive: true,
  },
];
