export const aiModels = [
  {
    provider: "meta",
    modelName: "Llama 3.3 70B",
    apiIdentifier: "meta-llama/llama-3.3-70b-instruct:free",
    contextWindow: 128000,
    costPer1kTokens: 0,
    maxTokens: 500,
    isActive: true,
  },
  {
    provider: "deepseek",
    modelName: "DeepSeek R1",
    apiIdentifier: "deepseek/deepseek-r1-0528:free",
    contextWindow: 163840,
    costPer1kTokens: 0,
    maxTokens: 8000,
    isActive: true,
  },
  {
    provider: "qwen",
    modelName: "Qwen3 Next 80B",
    apiIdentifier: "qwen/qwen3-next-80b-a3b-instruct:free",
    contextWindow: 262144,
    costPer1kTokens: 0,
    maxTokens: 500,
    isActive: true,
  },
  {
    provider: "google",
    modelName: "Gemma 3 27B",
    apiIdentifier: "google/gemma-3-27b-it:free",
    contextWindow: 131072,
    costPer1kTokens: 0,
    maxTokens: 500,
    isActive: true,
  },
  {
    provider: "mistral",
    modelName: "Mistral Small 3.1 24B",
    apiIdentifier: "mistralai/mistral-small-3.1-24b-instruct:free",
    contextWindow: 128000,
    costPer1kTokens: 0,
    maxTokens: 500,
    isActive: true,
  },
];
